import Contianer from './Contianer';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="container mx-auto">
        <Contianer>{children}</Contianer>
      </body>
    </html>
  );
}
